---
# tasks file for configure-repo role

- name: Create /etc/yum.repos.d/CentOS-Base.repo
  template:
    src:   etc/yum.repos.d/CentOS-Base.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo
    backup: yes
    mode: 0700
    owner: root
    group: root
    force: yes

- name: Create /etc/yum.repos.d/epel.repo
  template:
    src:   etc/yum.repos.d/epel.repo
    dest: /etc/yum.repos.d/epel.repo
    backup: yes
    mode: 0700
    owner: root
    group: root
    force: yes

- name: Install yum-plugin-s3-iam
  shell:
    creates: /etc/yum/pluginconf.d/s3iam.conf
    cmd: |
      aws s3 cp s3://{{RepositoryBucket}}/{{RepositoryFolder}}/yum/yum-plugin-s3-iam-1.2.2-1.noarch.rpm /root/yum-plugin-s3-iam-1.2.2-1.noarch.rpm
      yum install -y /root/yum-plugin-s3-iam-1.2.2-1.noarch.rpm
      rm -f /root/yum-plugin-s3-iam-1.2.2-1.noarch.rpm
